name: merge

on:
  pull_request_target:
    types: [opened, reopened, edited]

jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install commitlint and config-conventional
        run: npm install @commitlint/cli @commitlint/config-conventional
      - name: Setup commitlint config
        run: |
          echo 'extends: ["@commitlint/config-conventional"]' > .commitlintrc.yaml
      - name: Ensure PR title matches the conventional commit message format
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: echo "$TITLE" | npx commitlint
